### ISSUE TITLE
BROW/Slide-level multi-class subtyping task /feature_extract----error_code???

### ISSUE THREAD

**Issue by 464hee** [openmedlab/BROW#1]
![image](https://github.com/openmedlab/BROW/assets/100740023/34ee693a-9b52-420c-b888-4e9712659acf)
I keep a question about the image processing pipeline of extract_features.py, why is it necessary to use transforms.CenterCrop((224,224)) instead of transforms.Resize((224,224)) in the feature extraction, @wustone1995

**Comment by 464hee** [comment]
![415DCFD0-9B38-464b-A86A-06BF38C0D1B7](https://github.com/openmedlab/BROW/assets/100740023/ae0954e1-b060-47ca-a22f-8c29d1f4c466)
 transforms.CenterCrop((224,224))Crop the 224*224 size from the center region, if you accidentally input an image larger than 224*224, then you can't get the full image features?

**Comment by wustone1995** [comment]
In the slide-level-subtyping task, we employed a multiple instance learning framework, which necessitates the cropping of the original WSI images. The patch size is approximately 224, where the information acquired through center-cropping and resizing remains similar. This is one of the approaches adopted in the experiments.

**Comment by 464hee** [comment]
ok
